
spring.application.name=local-manager
server.port=8081

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# data source configuration
spring.datasource.url=jdbc:sqlite:local-manager.db
spring.datasource.driverClassName=org.sqlite.JDBC
